### ISSUE TITLE
Ending Script Tag

### ISSUE THREAD

**Issue by tetshi** [nemoDreamer/atom-language-coldfusion#6]
Currently, any ending </script> tags get rendered improperly. 

![script](https://cloud.githubusercontent.com/assets/2688290/5631624/e691f63e-9595-11e4-9d87-e7373002d190.PNG)

After removing this package, the ColdFusion syntax highlighting is gone, but the script tags render properly again.

**Comment by nemoDreamer** [comment]
Linked to #1.
